Complete e2 e challenge
helloextend/e2e-challenge pull request #3
Opened 2020-10-04 22:43 UTC by danielns8

2020-10-05 20:28 UTC, m-schrepel requested changes
There are some choices I'm curious about and one test that is passing that should not pass.

You have a good number of useful, reusable abstractions however, which is good. You thought a lot about having utility functions, though in some cases it would have been easier to read if they had been grouped together (for readability) instead of being so granular. 

A function should do one thing well, but when a function is only returning another function, something has been lost.

Anyway, looking forward to hearing back.

2020-10-05 20:28 UTC, m-schrepel commented on test/pageobjects/list.page.js
> +        return this.getBuildingInfo(this.getColumn(rank))
This seems like a lot of indirection to break out your 3 functions in this instance. 

Since you have a lot of functions that return other functions, it would be easier to read (to me) if your building info functions were all combined into one.

2020-10-05 20:28 UTC, m-schrepel commented on test/pageobjects/page.js
> +    waitToBeOnPage (timeout) {
Did you run into a problem where the page hadn't been loaded before you implemented this?

2020-10-05 20:28 UTC, m-schrepel commented on test/pageobjects/page.js
> +        return this.getTitle() === this.title;
Is this enough to know that you're on the right page? Wouldn't webdriverio already have a utility for waiting for a page to load in the first place?

2020-10-06 01:32 UTC, danesgi commented on test/pageobjects/list.page.js
> +        const tr = $$(`//table[3]//tr[${idx}]`);
Xpath because there wasn't an easier css option. The other alternative would be to get all the tables on the page and index into it.

2020-11-10 17:23 UTC, closed without merging